version: "3"
services:
  tomcat:
    build:
      context: ./
      args:
        TOMCAT_VERSION: 8.5.96-jdk8
    image: seanly/middset:tomcat-v8.5.96-jdk8
    container_name: tomcat
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    name: opsbox-network
    external: true
