version: '3'
services:
  minio:
    build: 
      context: ./
      args:
        - VERSION=RELEASE.2021-12-20T22-07-16Z
    image: seanly/midextra:minio-2021-12
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address :9001
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: minioroot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  default:
    name: opsbox-network

volumes:
    minio-data: